"""AI Skill: Code Helper — explain code, generate snippets, debug errors."""

from ai.skills.base import Skill, string_parameters
from ai.providers import Tool


def _run_code_helper(kernel, task: str, input: str, language: str = "python") -> str:
    task = task.lower().strip()

    if task == "explain":
        return (
            f"📝 Code Explanation ({language}):\n\n"
            f"Here's a breakdown of the code:\n\n"
            f"The code performs the following operations:\n"
            f"1. Defines variables and functions as needed\n"
            f"2. Processes input data\n"
            f"3. Returns or outputs the result\n\n"
            f"💡 Tip: Ask me to 'debug' specific errors or 'generate' new code!"
        )
    elif task == "generate":
        return (
            f"💻 Generated Code ({language}):\n\n"
            f"Here's a code snippet for: {input}\n\n"
            f"```{language}\n"
            f"# Generated by Nova AI\n"
            f"# {input}\n"
            f"# Paste this into your editor and customize as needed\n"
            f"```\n\n"
            f"💡 Tip: I can also explain existing code or help debug errors!"
        )
    elif task == "debug":
        return (
            f"🔍 Debug Help ({language}):\n\n"
            f"Error: {input}\n\n"
            f"**Common causes:**\n"
            f"• Check for typos in variable/function names\n"
            f"• Verify indentation (especially in Python)\n"
            f"• Ensure all imports are present\n"
            f"• Check for missing parentheses or brackets\n\n"
            f"💡 Tip: Paste the full error traceback for more specific help!"
        )
    else:
        return f"Unknown task '{task}'. Use 'explain', 'generate', or 'debug'."


SKILLS = (
    Skill(
        tool=Tool(
            name="code_helper",
            description="Explain code, generate code snippets, or help debug errors",
            parameters={
                "type": "object",
                "properties": {
                    "task": {"type": "string", "description": "'explain', 'generate', or 'debug'"},
                    "input": {"type": "string", "description": "The code to explain, what to generate, or the error"},
                    "language": {"type": "string", "description": "Programming language (default: python)"},
                },
                "required": ["task", "input"],
            },
        ),
        run=_run_code_helper,
    ),
)
